kind: List
metadata: {}
apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: tweeter-go
    labels:
      app: tweeter
  spec:
    replicas: 3
    selector:
      app: tweeter
    template:
      metadata:
        labels:
          app: tweeter
        annotations:
          k8s.mesosphere.io/roles: slave_public
      spec:
        containers:
        - name: server
          image: mesosphere/tweeter-go:latest
          imagePullPolicy: Always
          command:
          - "tweeter"
          - "--cassandra-addr=cassandra-dcos-node.cassandra.dcos.mesos"
          - "--cassandra-repl=3"
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 1
          ports:
          - name: http
            containerPort: 8080
            hostPort: 80
          resources:
            limits:
              cpu: 0.25
          env:
          - name: TWEETER_INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
- apiVersion: v1
  kind: Service
  metadata:
    name: tweeter
    labels:
      app: tweeter
  spec:
    selector:
      app: tweeter
    ports:
    - port: 80
      targetPort: http
