kind: List
metadata: {}
apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: oinker-go
    labels:
      app: oinker
  spec:
    replicas: 3
    selector:
      app: oinker
    template:
      metadata:
        labels:
          app: oinker
      spec:
        containers:
        - name: server
          image: karlkfi/oinker-go:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: oinker
    labels:
      app: oinker
  spec:
    selector:
      app: oinker
    ports:
    - port: 80
      targetPort: http
